FROM  ubuntu:lastest AS build

RUN apt-get update && apt-get install openjdk-22-jdk -y

COPY ..

RUN apt-get install maven -y
RUN mvn clean install

EXPOSE 8080

COPY --from=build /target/todo-0.0.1-SNAPSHOT.jar app.jar
ENTRYPOINT ["java", "-jar", "app.jar"]